baseURL = "https://blog.brigade.sh/"
languageCode = "en-us"
title = "Brigade Blog"
theme = "tale"

[author]
  name = "The Brigade Authors"

[params]
  faviconSizes = [ 16, 32, 48 ]

  # Google Analytics
  google_analytics_id = "UA-130516746-5"

[menu]
  [[menu.main]]
    name = "Brigade Home"
    url = "https://brigade.sh/"
    weight = 1
  [[menu.main]]
    name = "Docs"
    url = "https://docs.brigade.sh/"
    weight = 2
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/brigadecore/brigade"
    weight = 3

[markup]
  [markup.highlight]
    style = 'pygments'
