[build]
  publish = "public/"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.92.0"
  
[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "/index.xml"
  [headers.values]
    Access-Control-Allow-Origin = "*"
